DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS rides;

CREATE TABLE users (
  id INT GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
)

CREATE TABLE rides (
  id INT GENERATED ALWAYS AS IDENTITY,
  destination VARCHAR(255) NOT NULL,
  time VARCHAR(5) NOT NULL,
  date VARCHAR(8) NOT NULL,
  PRIMARY KEY(id)
)

